// @flow

export type Props = {
  onAgeChange: Function,
  onFeelTheSame: Function,
  onNameChange: Function,
  onRestart: Function,
  age: string,
  name: string,
  onSetStepCount: Function,
  renderStep: Function,
  onSetTitle: Function,
  Step: any,
  currentStep: number,
  onShareWithAdam: Function,
  onGoToStep: Function,
  myManLady: string,
  heShe: string,
  hisHer: string,
  himHer: string,
  gender: string,
  onGenderChange: Function,
  onUserInputSubmit: Function,
  onNext: Function,
  dontUnderstand: Object,
  letsContinue: Object,
  back: Object,
  classes: Object,
};
