export default {
  title: 'Peaceful Ending',
  description: 'This process will help soften the unpleasantness and negative feelings regarding the moment of transition, and the events regarding the transition, like the funeral and related things you might went through.',
  typeform: 'https://adamgoldman.typeform.com/to/Rwa8iu',
  testimonials: [
    {
      title: 'Minimized the absence',
      text: 'Pretty interesting ... to see things in reverse ... and the circus music was perfect.  It reduced the personal injury I felt to just a set of decisions that were made - no judgments...nothing personal…',
      name: 'Beth D\'Angelo',
      nameMeta: 'Mother of Sean, died in a car accident',
      imgSrc: '',
    },
    {
      title: 'Warm and comfy',
      text: 'When I think of him now, I am being directed to Tyler happy and smiling. Feels warm and comfy. I do tend to focus more on seeing Tyler before the incident when he was happy.',
      name: 'Elizabeth West',
      nameMeta: 'Mother of Tyler, died of suicide',
      imgSrc: '',
    },
    {
      title: 'I was living in this traumatized experience',
      text: 'This made me understand how intensively I was living in this traumatized experience. Like I literary was living it through every day every moment. I don\'t hold on to heavy, sad memories anymore. Like I don\'t need to force myself every day to tell me that something terrible happened. I can choose how to feel. it is great. And the reverse was fun',
      name: 'Vita Steina',
      nameMeta: 'Mother of Ralph, died from illness after long period in the hospital',
      imgSrc: '',
    },
    {
      title: 'Was I only thinking sad thoughts before?',
      text: 'Yes it’s better because there’s less negative punch. The reverse part actually makes you feel really silly, so of course I prefer the happy moment and feel better experiencing it this way. No bad feeling!',
      name: 'S.Z.',
      nameMeta: 'Mother of G, died after 1.5 years in the hospital',
      imgSrc: '',
    },
    {
      title: 'Thank you !!!',
      text: 'This way is better than it was before. Better, much better. Thank you !!!',
      name: 'Tracy Soussi',
      nameMeta: 'Mother of Aymen, died from illness',
      imgSrc: '',
    },
    {
      title: 'Took me to a healthy Anthony',
      text: 'It made me laugh inside, yet it took me to a healthy Anthony, which what he’d want for me. Unbelievable, unexpected, yet Real now, his corpse peaceful. I accept and release that burden so that Anthony will be at peace. God bless you!',
      name: 'Alexandra M. Rush',
      nameMeta: 'Mother of Anthony',
      imgSrc: '',
    },
  ],
  faq: [],
}
